services:
    adguard:
      image: adguard/adguardhome:latest
      container_name: adguard-home
      restart: unless-stopped

      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "3000:3000/tcp"
        - "80:80/tcp"
      volumes:
        - ./work:/opt/adguardhome/work
        - ./conf:/opt/adguardhome/conf
