services:
    adguard:
      image: docker.io/adguard/adguardhome:latest
      container_name: adguard-home
      restart: unless-stopped
      network_mode: host

      volumes:
        - ./work:/opt/adguardhome/work
        - ./conf:/opt/adguardhome/conf
